### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by crexlight** [karaokenerds/python-audio-separator#1]
Will there be GPU Torch CUDA demixing support?

**Comment by beveradb** [comment]
If you implement it (PRs welcome), or give me a strong nudge / some direction on how to add it 😉 

The only direction I'm likely to go myself in terms of speeding up the inferencing is to try and re-work one or two of the trained models to [work with TensorFlow Lite](https://coral.ai/docs/edgetpu/models-intro) so I can offload them to my Google Coral USB accelerator.
In my experience this approach can be as much as 100x faster / lower power than GPU inferencing, so I'm more interested in that as it would potentially unlock on-the-fly audio separation or at least enable me to provide a free hosted solution 👀

**Comment by crexlight** [comment]
Uh, i just realized that we can just download another onnxruntime with GPU support (pip install onnxruntime-gpu), then change:

self.device = torch.device("cuda")
self.run_type = ["CUDAExecutionProvider"]

in separator.py...

LOL, i didn't know that the default onnxruntime does not support the GPU...

**Comment by AntitrustEnthusiast** [comment]
If you don't mind importing `torch` in whatever file you're using `Separator()` in, you can do this:

```python
    separator = Separator(audio_file_path)
    if cuda:
        print("Running in GPU mode")
        separator.device = torch.device("cuda")
        separator.run_type = ["CUDAExecutionProvider"]
```

Works on my machine without modifying the library. Would be nice to have as a constructor argument/CLI param, though.

Thanks for the library!

**Comment by beveradb** [comment]
Just published version `0.3.2` with `use_cuda` param - please test @crexlight & @AntitrustEnthusiast 😃 

(I get `AssertionError: Torch not compiled with CUDA enabled` when I try it and I don't have an Nvidia GPU to test with)

If there's anything else I should add to the docs, e.g. a section explaining you need to install a specific version of Torch or something for GPU support please let me know!

**Comment by AntitrustEnthusiast** [comment]
It sort of works. I also get `AssertionError: Torch not compiled with CUDA enabled`, but it works if I follow these steps:
```bash
pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html
```
Although note this means you'll be on the latest stable Torch, so 2.0.x right now.

Someone better at Torch/pip could probably do this in a way that doesn't violate the 1.3.x dependency of this library. But 2.0.x doesn't seem to break anything, so I'm happy!

Thanks!

**Comment by beveradb** [comment]
In version 0.5 I've upgraded to Torch 2 and added a couple more debug log entries for CUDA support: https://github.com/karaokenerds/python-audio-separator/commit/055d5066b407da79798ab015f52e9b1a2b38bcdb

Can you see if that's enough for this to work out of the box now without needing a separate pip install?

**Comment by AntitrustEnthusiast** [comment]
Sorry for the delay! A fresh install doesn't seem to work out of the box, unfortunately. Normally I'd recommend a 2nd `requirements.txt` for GPU setup, but I'm not sure how that works with poetry.

Full traceback of error:
```
2023-07-22 16:36:44.659 - INFO - cli - Separator beginning with input file: C:\Misc\test.flac
Traceback (most recent call last):
  File "C:\dev\python-audio-separator\.venv\Scripts\audio-separator", line 6, in <module>
    sys.exit(main())
  File "C:\dev\python-audio-separator\audio_separator\utils\cli.py", line 43, in main
    separator = Separator(
  File "C:\dev\python-audio-separator\audio_separator\separator.py", line 97, in __init__
    raise Exception("CUDA requested but not available with current Torch installation. Do you have an Nvidia GPU?")
Exception: CUDA requested but not available with current Torch installation. Do you have an Nvidia GPU?
```

**Comment by beveradb** [comment]
I've now gotten around to testing this properly on a system with an Nvidia GPU (through Runpod: https://www.runpod.io/console/gpu-cloud)

It's still a bit of a compromise as I haven't figured out any way to package `audio-separator` using poetry to include the right dependencies for GPU transcoding whilst still working out of the box for CPU users too.

However, I've added clear instructions to the README now:
https://github.com/karaokenerds/python-audio-separator#extra-installation-steps-for-use-with-a-gpu

and have tested it myself (wow, separation literally takes a few seconds rather than a few minutes!), so I think it's fair to close this now 😄 

If you or anyone else figures out how to package/publish so it works out of the box without extra steps please let me know!

**Comment by hero-intelligent** [comment]
https://python-poetry.org/docs/managing-dependencies/#optional-groups

This might help. I apologize first that I may not be able to solve this problem directly for I'm not a programmer, but you all can try and see if it works.
