### ISSUE TITLE
  [Feature request] Docker image / "probable better method to build package for GPU support with clean install step, and testing steps" 

### ISSUE THREAD

**Issue by hero-intelligent** [karaokenerds/python-audio-separator#16]
>              Thanks for sharing 😄 
> I certainly like the idea of having a docker image ready to run for anyone who wants to use audio-separator without any installation required; that should also make it easier for people to get it up and running on different machines.
>
> However, I gotta say that dockerfile you linked is pretty wild 😅 
> Not sure I'd want to use it directly but there's probably some learnings I could take from it and try to publish a docker image from this repo for people to be able to conveniently run `audio-separator` in docker.
>
> My gut feeling is that should be possible with a much more minimal dockerfile/image - e.g. why are you compiling python from source?
> Why not just start with a base image using the [official pytorch images](https://hub.docker.com/r/pytorch/pytorch/tags) (e.g. the latest CUDA one [2.0.1-cuda11.7-cudnn8-runtime](https://hub.docker.com/layers/pytorch/pytorch/2.0.1-cuda11.7-cudnn8-runtime/images/sha256-82e0d379a5dedd6303c89eda57bcc434c40be11f249ddfadfd5673b84351e806?context=explore) )?
> 
> Also, hope you don't mind but I've edited the title of this issue to remind me to add a docker image for `audio-separator`!

_Originally posted by @beveradb in https://github.com/karaokenerds/python-audio-separator/issues/10#issuecomment-1715142134_ , which may be off line, so I'm here for opening another issue. Sorry for the convenience.

**Comment by beveradb** [comment]
FYI I've now published docker images for all common platforms (including specifically for CUDA GPUs) with usage instructions:

https://github.com/karaokenerds/python-audio-separator#usage-in-docker-

Let me know if that doesn't work for you! :)
