### ISSUE TITLE
[CICD] building a docker image that includes RVC and audio-seperator

### ISSUE THREAD

**Issue by CenekSanzak** [karaokenerds/python-audio-separator#17]
I am building a Dockerfile from my github actions, I want it to use cuda version, It works with RVC now, I added audio-seperator added the lines in the readme for deleting onnx-runtime and installing onnxruntime-gpu. But onnxruntime is already installed and installing it after deleting the onnxruntime throws error about the audio-separator package `audio-separator 0.7.3 requires onnxruntime<2.0,>=1.15; sys_platform != "darwin" and platform_machine != "arm64", which is not installed.`. It doesn't work in the docker after that message: `module ‘onnxruntime’ has no attribute ‘InferenceSession’`. It works when I don't uninstall onnxruntime and reinstall onnxruntime-gpu but it works really slow, so I think that it is not using cuda. What do you suggest for that? How can I solve that?

**Comment by beveradb** [comment]
Sorry, I'm not really sure how to help you - can you link to your Dockerfile or code or something so I can test myself?
Also, what platform are you on?
I've only tested audio-separator on macOS (Apple Silicon) and Linux.

**Comment by beveradb** [comment]
Hey @CenekSanzak, sorry for the slow reply on this, didn't have much capacity for hobby projects till now but i'm focusing on `audio-separator` a bit more over the festive period.

I've just pushed a bunch of updates to `audio-separator` to make the GPU/other hardware acceleration detection a lot more robust and remove the need for passing in the `--use_cuda` or `--use_coreml` arguments.

I've also repackaged it to relax the dependencies and remove the CPU version of onnxruntime from the dependencies; in fact no version of onnxruntime is a default dependency any more, instead people have to install `audio-separator` with a specific extra (either `gpu`, `silicon`, or `cpu`)

So for GPU users, in theory all most people should need to do is install `audio-separator` like this:
`pip install audio-separator[gpu]`

Check out the updated readme:
https://github.com/karaokenerds/python-audio-separator#-nvidia-gpu-with-cuda-acceleration

I've tested this pretty robustly on a Runpod with a RTX A4000 GPU but I may still have missed something. 
Please let me know if you have any issues!
