### ISSUE TITLE
PTH & CKPT Support

### ISSUE THREAD

**Issue by shalevc1098** [karaokenerds/python-audio-separator#18]
Hello, can you please add PTH support? Thanks!

**Comment by hunmer** [comment]
> Hello, can you please add PTH support? Thanks!

https://github.com/seanghay/uvr

**Comment by shalevc1098** [comment]
> > Hello, can you please add PTH support? Thanks!
> 
> https://github.com/seanghay/uvr

how can i use it in my code?

**Comment by hunmer** [comment]
> > > Hello, can you please add PTH support? Thanks!
> > 
> > 
> > https://github.com/seanghay/uvr
> 
> how can i use it in my code?

see: https://github.com/seanghay/uvr/blob/bd882211bbe197a735ba021b4ddb4dd8bc846086/separate.py#L101

**Comment by beveradb** [comment]
Hello! :) 
Pull requests to add features are very much welcome - but I personally will not be adding support for other models myself, as `audio-separator` already works great for my use case (karaoke video production) so my motivation is fairly low to develop more functionality.

I'm also personally not keen on diving back into the UVR code again any time soon as it's kinda spaghetti code, but if you're interested in writing code yourself, I'd happily pair with you on a zoom call or something to help you get up to speed with it! :) 

In case it helps, most of the core logic in this project was cherry picked from https://github.com/Anjok07/ultimatevocalremovergui/blob/master/separate.py

**Comment by shalevc1098** [comment]
> Hello! :) Pull requests to add features are very much welcome - but I personally will not be adding support for other models myself, as `audio-separator` already works great for my use case (karaoke video production) so my motivation is fairly low to develop more functionality.
> 
> I'm also personally not keen on diving back into the UVR code again any time soon as it's kinda spaghetti code, but if you're interested in writing code yourself, I'd happily pair with you on a zoom call or something to help you get up to speed with it! :)
> 
> In case it helps, most of the core logic in this project was cherry picked from https://github.com/Anjok07/ultimatevocalremovergui/blob/master/separate.py

the problem is, i already looked at the separate.py of UVR, but couldn't figure out anything, thus opened this issue. i want to automate the process of vocal separation. the first uses kim vocal 2, which is fine because it is onnx. the other three use pth, and this is where the problem starts.

**Comment by ajayarora1235** [comment]
@beveradb  @shalevc1098 i'm down to help out with this, but would def want to pair over zoom this weekend/early next week to confirm the general approach/pseudocde! good practice for me contributing to open source libraries anyway

**Comment by beveradb** [comment]
Awesome, thankyou @ajayarora1235 😄  

I'm actually at a karaoke producers convention and then my wedding anniversary this weekend so early next week would be better for me - but if you want to get started sooner than that and have any questions or confusing things while trying to get yourself set up to develop feel free to reach out to me directly; I'm @beveradb on various platforms (including e.g. telegram), and I'm +447835171222 on whatsapp or SMS etc.

**Comment by c469591** [comment]
Hi, is it possible to use the 23c model already?
I use
separator.load_model('MDX23C-8KFFT-InstVoc_HQ.ckpt')
But the display
FileNotFoundError: [Errno 2] No such file or directory: 'models\\MDX23C-8KFFT-InstVoc_HQ.ckpt.onnx'

**Comment by beveradb** [comment]
@c469591 no, nobody has implemented that yet. 

If you'd like to try and implement it, feel free to reach out to me directly if you need help getting started :)

**Comment by Subraiz** [comment]
@beveradb would you be interested in developing support for .pth files if my company could fund your development time?

**Comment by beveradb** [comment]
Absolutely @Subraiz ! I've recently lost my day job so would jump at that opportunity 😄 
andrew@beveridge.uk

**Comment by beveradb** [comment]
I am now actively working on this 👀

**Comment by beveradb** [comment]
Hey folks, FYI I've been working on adding support for VR models this week, and I released `audio-separator` version `0.14` earlier today with initial support for VR models!

Please give it a try and see if it works for you!

I'm still working on documentation, tests and some packaging issues but the package on PyPI should "just work".

There's a few new CLI parameters including `--list_models` which prints all the models which are supported out of the box (basically every MDX or VR model supported by UVR), and the interface has changed slightly (you now specify model filename with extension too).

I will be working on "ensemble mode" and model chaining functionality later this month with the goal of outputting multiple stems (not just primary/secondary), so watch this space!
