### ISSUE TITLE
expose output format as argument

### ISSUE THREAD

**Issue by AntitrustEnthusiast** [karaokenerds/python-audio-separator#2]
Hi, thanks for the great library/CLI tool!

One minor problem when running this on a lot of inputs is that WAV output files will eat up space very fast. To help alleviate this, supporting an output format/subtype argument/CLI param would be much appreciated.

First, I add `output_format="WAV"` and `output_subtype` as optional `Separator` constructor args.

Then, I add this to the `Separator` constructor:
```python
# self.subtype replaces self.wav_type_set
self.subtype = output_subtype
self.format = output_format
if self.subtype is None and output_format == "WAV":
    self.subtype = "PCM_16"
```

And finally replace the `sf.write()` call with this:  
```python
sf.write(stem_path, stem_source, samplerate, subtype=self.subtype, format=self.format)
```

This maintains existing behavior of 16-bit WAV output with no config, while allowing user to do this:  
`separator = Separator(audio_file_path, format="FLAC")`
or any other format `soundfile` supports (which is quite a few)

Current workaround would just be importing soundfile and doing this manually,  but that's not easy for CLI users, and adds the overhead of reading/writing the files an extra time.

**Comment by beveradb** [comment]
Version 0.4 onwards implements this (`output_format` class arg / CLI param)
Thanks for the suggestion!
