### ISSUE TITLE
huge VRAM comsuption compared to uvr

### ISSUE THREAD

**Issue by Pimax1** [karaokenerds/python-audio-separator#21]
Hi, 

uvr doesnt use much vram (about 4gb VRAM) but this code eats up suddenly all my available VRAM at inference (up to 15GB VRAM)

I compared UVR and this repo using the same MDX models and the same thing happen for all models. 
That's preventing me to run other gpu intensive tools at the same time. 

any idea why there are huge VRAM spikes with audio separator ? 

thanks

**Comment by beveradb** [comment]
Not off the top of my head, no - sorry! That's strange though, most of the code in this came straight from UVR.

That said, there's a pretty good chance that it's related to the "batch" processing in UVR, see e.g.

https://github.com/Anjok07/ultimatevocalremovergui/blob/master/gui_data/change_log.txt#L6
> "Added "Batch Mode" for MDX-Net to increase performance. Batch Mode is more memory efficient."
 
Which I think is referring to the `mdx_batch_size` param and batching of chunks, in the UVR separation code:
https://github.com/Anjok07/ultimatevocalremovergui/blame/master/separate.py#L173

I didn't keep that functionality when I copied/refactored code over to `audio-separator` as I was trying to keep this as simple and clean as possible (and honestly it was really hard to unpick what was even going on in the spaghetti code of UVR, a lot of stuff was tightly coupled to the GUI and I kinda thought the batching was part of that).

If you want to take a stab at pulling together a PR to add that batching from UVR into audio-separator please feel free, if it did reduce memory consumption at no other cost it would be a very welcome improvement 😄

**Comment by beveradb** [comment]
Hey @Pimax1 please could you try the latest version of `audio-separator` (version 0.14) - there are now parameters which you can pass into the inferencing process to control this, e.g. batch and window size.

I also find the VR models require far less RAM if you use a smaller batch size, so that may be worth trying!

If I don't hear from you in the next week or two, I'll close this issue as it's a little old now. 🙇
