### ISSUE TITLE
Allows the model to be loaded into memory for repeated use!

### ISSUE THREAD

**Issue by 5118Python** [karaokenerds/python-audio-separator#24]
Thank you for your excellent work. Please provide a class that allows the model to be loaded into memory for repeated use, instead of having to reload the model every time. This would facilitate creating an application service. Thank you.

**Comment by beveradb** [comment]
PRs very much welcome to add this functionality!

**Comment by himekifee** [comment]
This would be really helpful. Loading and unloading models for thousands of times is such a pain.

**Comment by beveradb** [comment]
Hey @5118Python  or @himekifee, please could you check out the latest version `0.12.0`?

Updated docs here: 
https://github.com/karaokenerds/python-audio-separator#batch-processing-or-processing-with-multiple-models

I believe I've implemented this in a way which should work for y'all - at least in my testing, it definitely did save some time when separating multiple files in a row using the same model 😄 

If it's not working as you'd expect or like it to, please provide your debug logs by setting `--log_level=debug` for me to understand a bit more of how you're using it!

Happy new year!

**Comment by himekifee** [comment]
Brilliant! I will test it with 2000+ audio later. My env is kinda broken right now. Will give you the feedback later, and happy new year!

**Comment by himekifee** [comment]
Great news! The loading in memory works perfectly with about 2000+ files. However, I found out the model loading is much less than the actual separation time, so the gain is not that visible. Anyway, that's some progress. I would consider doing some file loading queue if I want to accelerate further, as the librosa loading seems to take quite a bit of time.

**Comment by beveradb** [comment]
Nice, thanks for confirming!
Sorry it didn't bring the performance gains you were hoping for.

PRs are of course always welcome - if you do decide to dive in to trying to improve batch loading performance further yourself, I'd be more than happy to jump on a call and help you get up to speed / talk you through what I know any time, or help in any way I can;
My email is andrew@beveridge.uk and phone number is +1 (803) 636-3267

I'll close this issue for now as it's technically resolved :)
