### ISSUE TITLE
Error Installing audio-separator with GPU Support: Dependency Conflicts and CUDA Library Issue

### ISSUE THREAD

**Issue by tobq** [karaokenerds/python-audio-separator#25]
### Error Installing audio-separator with GPU Support: Dependency Conflicts and CUDA Library Issue

**Problem Description:**
I'm encountering an issue while setting up GPU support for the audio-separator package as per the README instructions. After following the installation steps, I'm faced with dependency conflicts, and attempting to run the separator defaults to CPU usage due to a missing CUDA library.

**Steps to Reproduce:**
```bash
conda create -n audio-separator python=3.9
conda activate audio-separator
pip install audio-separator
pip uninstall torch onnxruntime
pip cache purge
pip install torch "optimum[onnxruntime-gpu]"
```

**Expected vs Actual Behavior:**
Expected: Successful installation of the audio-separator with GPU support.
Actual: Encountered dependency conflicts and a missing CUDA library error.

**Error Logs:**
```
Downloading frozenlist-1.4.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.0/228.0 kB 4.0 MB/s eta 0:00:00
Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 7.7 MB/s eta 0:00:00
Downloading yarl-1.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (304 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.3/304.3 kB 4.0 MB/s eta 0:00:00
Installing collected packages: sentencepiece, pytz, xxhash, tzdata, tqdm, safetensors, regex, pyyaml, python-dateutil, pyarrow-hotfix, pyarrow, psutil, multidict, fsspec, frozenlist, dill, attrs, async-timeout, yarl, responses, pandas, onnxruntime-gpu, multiprocess, huggingface-hub, aiosignal, torch, tokenizers, aiohttp, transformers, accelerate, datasets, optimum, evaluate
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.12.2
    Uninstalling fsspec-2023.12.2:
      Successfully uninstalled fsspec-2023.12.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audio-separator 0.8.0 requires onnxruntime<2.0,>=1.15; sys_platform != "darwin" and platform_machine != "arm64", which is not installed.
Successfully installed accelerate-0.25.0 aiohttp-3.9.1 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 datasets-2.15.0 dill-0.3.7 evaluate-0.4.1 frozenlist-1.4.0 fsspec-2023.10.0 huggingface-hub-0.19.4 multidict-6.0.4 multiprocess-0.70.15 onnxruntime-gpu-1.16.3 optimum-1.15.0 pandas-2.1.4 psutil-5.9.6 pyarrow-14.0.1 pyarrow-hotfix-0.6 python-dateutil-2.8.2 pytz-2023.3.post1 pyyaml-6.0.1 regex-2023.10.3 responses-0.18.0 safetensors-0.4.1 sentencepiece-0.1.99 tokenizers-0.15.0 torch-2.1.1 tqdm-4.66.1 transformers-4.36.0 tzdata-2023.3 xxhash-3.4.1 yarl-1.9.4
```

**Environment Details:**
- CUDA Version: 12.2
- PyTorch Version: 2.1.1+cu121
- Operating System: Ubuntu

**Attempts to Resolve:**
I tried to manually install `onnxruntime`, which seems to solve the error, however when I actually run audio-separation, I see 0 GPU utilisation

**Request for Specific Help:**
Any guidance on resolving these dependency conflicts and the CUDA library issue would be greatly appreciated.

**Reference to Documentation:**
I followed the GPU setup instructions from the [audio-separator README](https://github.com/karaokenerds/python-audio-separator/blob/main/README.md).

**Comment by Michel-Lima** [comment]
![cuda](https://github.com/karaokenerds/python-audio-separator/assets/16857737/1c0b9b58-53df-442d-af29-dad4a7eb0a70)
i'm having the same problem! everything in
![image](https://github.com/karaokenerds/python-audio-separator/assets/16857737/39b07873-d231-4981-8c63-dcfecb1c5ee2)
stalled without error but the gpu is 0% used and the cpu is being used.

**Comment by beveradb** [comment]
Hey @tobq and @Michel-Lima, thanks for trying `audio-separator` and for reaching out about this!

Apologies for the slow reply, haven't had the capacity to work on my hobby project repos much recently but I'm focusing on them a little more over the festive period.

I've just pushed a bunch of updates to `audio-separator` to make the GPU/other hardware acceleration detection a lot more robust and remove the need for passing in the `--use_cuda` or `--use_coreml` arguments.

I've also repackaged it to relax the dependencies and remove the CPU version of onnxruntime from the dependencies; in fact no version of onnxruntime is a default dependency any more, instead people have to install `audio-separator` with a specific extra (either `gpu`, `silicon`, or `cpu`)

So for GPU users, in theory all most people should need to do is install `audio-separator` like this:
`pip install audio-separator[gpu]`

Check out the updated readme:
https://github.com/karaokenerds/python-audio-separator#-nvidia-gpu-with-cuda-acceleration

I've tested this pretty robustly on a Runpod with a RTX A4000 GPU but I may still have missed something. 
Please let me know if you have any issues!

**Comment by beveradb** [comment]
Ahhh, @tobq actually I just re-read your initial message and realised you're trying to use CUDA 12;

That won't work yet, ONNX Runtime doesn't yet support CUDA 12: 
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

If you downgrade to CUDA 11.8 and install pytorch from the CUDA 11.8 wheel index:
`pip install --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

and use the latest version of `audio-separator` (which as mentioned above, now has more robust detection and logging of CUDA details), I believe it should work! 🤞 

Please re-open this issue if it still doesn't work for you, and provide debug logs from `audio-separator` with `--log_level debug` 🙇
