### ISSUE TITLE
run under cuda

### ISSUE THREAD

**Issue by ischeck** [karaokenerds/python-audio-separator#26]
run under cuda
form "https://pytorch.org/get-started/locally/"
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by beveradb** [comment]
Hey, thanks for the note about this! 

I've just pushed a bunch of updates to `audio-separator` to make the GPU/other hardware acceleration detection a lot more robust and remove the need for passing in the `--use_cuda` or `--use_coreml` arguments.

I've also repackaged it so for GPU users, in theory all most people should need to do is install it with the `[gpu]` extra like so:
`pip install audio-separator[gpu]`

However I know it's not always that easy so I've updated the README with clearer instructions for GPU users:
https://github.com/karaokenerds/python-audio-separator#-nvidia-gpu-with-cuda-acceleration

That includes a section where I explicitly suggest that `cu118` index URL; it's just something which is somewhat environment specific and will hopefully become unnecessary once CUDA 12 becomes more widely supported :)
