### ISSUE TITLE
MDX23C-8KFFT-InstVoc_HQ_2.ckpt model

### ISSUE THREAD

**Issue by yassinebelatar** [karaokenerds/python-audio-separator#30]
Hello I found a model mapper in uvr {
    "UVR_MDXNET_1_9703": "UVR-MDX-NET 1",
    "UVR_MDXNET_2_9682": "UVR-MDX-NET 2",
    "UVR_MDXNET_3_9662": "UVR-MDX-NET 3",
    "UVR_MDXNET_KARA": "UVR-MDX-NET Karaoke",
    "UVR_MDXNET_Main": "UVR-MDX-NET Main",
    "UVR-MDX-NET-Inst_1": "UVR-MDX-NET Inst 1",
    "UVR-MDX-NET-Inst_2": "UVR-MDX-NET Inst 2",
    "UVR-MDX-NET-Inst_3": "UVR-MDX-NET Inst 3",
    "UVR-MDX-NET-Inst_4": "UVR-MDX-NET Inst 4",
    "UVR-MDX-NET-Inst_Main": "UVR-MDX-NET Inst Main",
    "UVR-MDX-NET-Inst_Main_2": "UVR-MDX-NET Inst Main 2",
    "UVR-MDX-NET-Inst_HQ_1": "UVR-MDX-NET Inst HQ 1",
    "UVR-MDX-NET-Inst_HQ_2": "UVR-MDX-NET Inst HQ 2",
    "UVR-MDX-NET-Inst_HQ_3": "UVR-MDX-NET Inst HQ 3",
    "UVR_MDXNET_KARA_2": "UVR-MDX-NET Karaoke 2",
    "Kim_Vocal_1": "Kim Vocal 1",
    "Kim_Vocal_2": "Kim Vocal 2",
    "Kim_Inst": "Kim Inst",
    "MDX23C-8KFFT-InstVoc_HQ.ckpt": "MDX23C-InstVoc HQ",
    "MDX23C-8KFFT-InstVoc_HQ_2.ckpt": "MDX23C-InstVoc HQ 2",
    "MDX23C_D1581.ckpt": "MDX23C-InstVoc D1581",
    "Reverb_HQ_By_FoxJoy": "Reverb HQ"
} when trying to use MDX23C-8KFFT-InstVoc_HQ.ckpt it doesnt work !

**Comment by beveradb** [comment]
Nobody has implemented support for checkpoint (CKPT) models yet;

See https://github.com/karaokenerds/python-audio-separator/issues/18
