### ISSUE TITLE
Supporting VR Architecture models like HP5

### ISSUE THREAD

**Issue by KevinWang676** [karaokenerds/python-audio-separator#37]
Hi, I wonder if you are going to support VR Architecture models like HP5 as well. Thanks!

**Comment by zhzhongshi** [comment]
#36

**Comment by beveradb** [comment]
Thanks @zhzhongshi - yep, I've literally been working on this all week and released `audio-separator` verison `0.14` earlier today! 😅 

Please give it a try and see if it works for you!

I'm still working on documentation, tests and some packaging issues (conda build failed, sigh) but the package on PyPI should "just work" - there's a new CLI parameter `audio-separator --list_models` which just prints all the models which are supported out of the box!

**Comment by zhzhongshi** [comment]
by install these it works.
```
pyrubberband
librosa==0.10.0
samplerate==0.2.1
```
thank you.

**Comment by beveradb** [comment]
Thanks for the report - I hadn't tested on Windows, and unfortunately I still haven't managed to get cross-platform end to end tests working in CI (that's on my to-do list though!)

I've now published version `0.14.4` which removes the `pyrubberband` dependency and includes `samplerate` as a dependency (which is somehow required by librosa on windows but not mac/linux...)

All currently-supported model types now work out of the box on Windows after `pip install audio-separator[cpu]`:
 
<img width="812" alt="image" src="https://github.com/karaokenerds/python-audio-separator/assets/757713/b496bee2-9d90-432f-9e57-a153b69b2343">
