### ISSUE TITLE
[Feature] Ability to only keep the vocals/karaoke audio file

### ISSUE THREAD

**Issue by CHFR-wide** [karaokenerds/python-audio-separator#4]
Arguably not a critical feature since it would be very easy for me to delete the extra file after the separation,
but I think it could be convenient to have a parameter that allows us to only keep the karaoke or vocals stream.

**Comment by beveradb** [comment]
Thanks for the suggestion, added in version `0.6.4` 😄
 
Documented in the [README](https://github.com/karaokenerds/python-audio-separator#command-line-interface-cli), CLI param is e.g. `--single_stem=instrumental`

It shaves off a couple of seconds, too, so could be valuable for folks with no use for one of the stems!
