### ISSUE TITLE
在分离带有二胡声的音频中，二胡声分离不出去，比如兰亭序，这该采用什么模型，有那种直接全部分离出去的模型吗？

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [karaokenerds/python-audio-separator#46]
在分离带有二胡声的音频中，二胡声分离不出去，比如兰亭序，这该采用什么模型，有那种直接全部分离出去的模型吗？

**Comment by beveradb** [comment]
Hi, sorry I don't speak Chinese but google translate gave me this translation of your message:

"When separating audio with erhu sound, the erhu sound cannot be separated, such as the Lanting sequence. What model should be used? Is there a model that can directly separate all the sounds?"

Unfortunately I don't really know what you're asking for as I don't know what "erhu sound" means or what "Lanting" was supposed to translate to.

The only suggestion I can make is that you experiment with different models (see `audio-separator --list_models` for all options). 
If you're trying to keep backing vocals, try the `UVR_MDXNET_KARA_2.onnx` model, or if you're trying to separate drums, guitar, piano etc. as well as vocals, try the `htdemucs_6s.yaml` model.

Good luck! 🙇 

Google translated response:

不幸的是，我真的不知道你在要求什么，因为我不知道“二胡声”是什么意思，也不知道“兰亭”应该翻译成什么。

我可以提出的唯一建议是您尝试不同的模型（有关所有选项，请参阅 `audio-separator --list_models`）。
如果您想继续伴奏人声，请尝试 `UVR_MDXNET_KARA_2.onnx` 模型，或者如果您想将鼓、吉他、钢琴等与人声分开，请尝试“htdemucs_6s.yaml”模型。

祝你好运！ 🙇

**Comment by beveradb** [comment]
I never got a response from you, but either way - I recommend switching to the RoFormer models which outperform the MDX ones IMO and make this issue redundant.

Check out e.g. `model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt` which is now supported from audio-separator version 0.17.1 onwards 😄
