### ISSUE TITLE
audio-separator: error: unrecognized arguments: --model_name=UVR_MDXNET_KARA

### ISSUE THREAD

**Issue by jonata** [karaokenerds/python-audio-separator#47]
Hi! I'm getting this error when trying to set a `model_name`:

`audio-separator: error: unrecognized arguments: --model_name=UVR_MDXNET_KARA_2`

I see there is an example using this option on README.

I'm using Python 3.10.

**Comment by beveradb** [comment]
Hey @jonata , sorry about that, I must have missed those examples in the README when I moved from `model_name` to `model_filename` in version 0.13 a couple of months ago.

I've just pushed a commit updating the README: 
https://github.com/karaokenerds/python-audio-separator/commit/59e72e27caf0f06c6d1b0ddb28c07ad864075127

**Comment by jonata** [comment]
Thanks for the fix!

By the way, if I may suggest, it would be great to have some more detailed instructions on how to download the models. I see some broken links or/and obscure ways to find the specific files. Thanks again!!

**Comment by beveradb** [comment]
Ah, maybe there's some misunderstanding about how to use `audio-separator` which could be improved in the documentation wording;

You do not need to download any files yourself - `audio-separator` does that automatically for you!
To see a list of supported models, run `audio-separator --list_models`

Anything file listed in that output can be specified with the `--model_name` parameter and it will be automatically downloaded to the `--model_file_dir` (default: /tmp/audio-separator-models/) on first usage.

Please let me know once you get it working for you, and if you have any suggestions for how I can better explain this in the README, I'm very keen for feedback!

**Comment by jonata** [comment]
> Any file listed in that output can be specified with the --model_name parameter (e.g. --model_name UVR-MDX-NET-Inst_HQ_3.onnx) and it will be automatically downloaded to the --model_file_dir (default: /tmp/audio-separator-models/) on first usage.

You mean `--model_filename` 😆

I got it now! Thanks @beveradb !!
