### ISSUE TITLE
Issue with Files Being Overwritten When Batch Processing Audio Files

### ISSUE THREAD

**Issue by soutlu** [karaokenerds/python-audio-separator#48]
I encountered a problem while using the batch processing feature of audio-separator. I attempted to process two audio files (1.wav and 2.wav) simultaneously, expecting to get separate audio files for each. However, I faced an issue where, regardless of the number of files processed, the output audio files seem to always get overwritten by the first processed audio file, leaving only a file named 1_(Vocals)_UVR-MDX-NET-Inst_HQ_3.wav.

Here is how I executed the command:

```python
from audio_separator.separator import Separator

# Initialize the Separator with other configuration properties below
separator = Separator()

# Load a model
separator.load_model(model_filename="UVR-MDX-NET-Inst_HQ_3.onnx")

# Separate multiple audio files without reloading the model
output_file_paths_1 = separator.separate("1.WAV")

output_file_paths_2 = separator.separate("2.WAV")

```

I expected each original audio file to have its corresponding separated audio outputs, rather than being overwritten. Is this an issue with my operation, or is it a bug in the software? Has anyone encountered a similar issue and can offer some advice on how to resolve it?

**Comment by beveradb** [comment]
Sorry to hear that, that sounds very much like a bug which is probably my bad. 
I'll look into fixing it tomorrow, apologies for the inconvenience.
I really need to write some integration unit tests for this project 😅

**Comment by beveradb** [comment]
Hey, thanks for flagging this, sorry it took me a few days to get around to fixing.

The latest release, version `0.16.1` or newer should no longer have this issue, and I'm working on adding a test to prevent this from ever occurring again.

In case you're curious, here's the fix commit: https://github.com/karaokenerds/python-audio-separator/commit/3c23878fafffaa79c74c2d49610b69fd38c9e8b1

Feel free to re-open or tag me if you have any other issues!

Cheers,
Andrew
