### ISSUE TITLE
Large instrumental bleedthrough in some vocal tracks

### ISSUE THREAD

**Issue by masonasons** [karaokenerds/python-audio-separator#49]
I'm using your python library with mdx net inst HQ 3 and 4 models. Sometimes, vocal tracks have quite a bit of instrumental bleedthrough in them. This doesn't happen with UVR with either of these models. I use the default settings. I've tried with denoise, different normalization, etc, same result.

**Comment by beveradb** [comment]
Sorry to hear that! Could you provide an example file which seems to have different results between UVR and audio-separator, with an example audio-separator command-line call and debug log output (add `-d`) so I can try and investigate?

(I don't experience any similar issue myself, so this is a bit confusing!)

**Comment by GoombaFCU** [comment]
I have same issue with MDX-NET Inst HQ 3 too, haven't tried Inst HQ 4 yet. Here's the example:
<img width="496" alt="example" src="https://github.com/karaokenerds/python-audio-separator/assets/43847136/37b53c6b-8b85-4159-b488-12bfebca2298">

Both tracks are the vocal parts of the same song splited with MDX-NET Inst HQ 3. The top track is from UVR5, and the down track is from audio-separator. All settings set to default, but the instrumental bleed in audio-separator version is even more apparent.

**Comment by beveradb** [comment]
FYI folks, I recommend switching to the RoFormer models which outperform the MDX ones IMO and make this issue redundant.

Check out e.g. `model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt` which is now supported from `audio-separator` version `0.17.1` onwards 😄
