### ISSUE TITLE
Some VR Arch models show the error: librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere

### ISSUE THREAD

**Issue by Eddycrack864** [karaokenerds/python-audio-separator#52]
Hello, some VR Arch models (specifically: 3_HP-Vocal-UVR.pth, 4_HP-Vocal-UVR.pth, UVR-BVE-4B_SN-44100-1.pth) show the error:
```py
Traceback (most recent call last):
  File "/usr/local/bin/audio-separator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/audio_separator/utils/cli.py", line 177, in main
    output_files = separator.separate(args.audio_file)
  File "/usr/local/lib/python3.10/dist-packages/audio_separator/separator/separator.py", line 634, in separate
    output_files = self.model_instance.separate(audio_file_path)
  File "/usr/local/lib/python3.10/dist-packages/audio_separator/separator/architectures/vr_separator.py", line 172, in separate
    self.primary_source = self.spec_to_wav(y_spec).T
  File "/usr/local/lib/python3.10/dist-packages/audio_separator/separator/architectures/vr_separator.py", line 324, in spec_to_wav
    wav = spec_utils.cmb_spectrogram_to_wave(spec, self.model_params, is_v51_model=self.is_vr_51_model)
  File "/usr/local/lib/python3.10/dist-packages/audio_separator/separator/uvr_lib_v5/spec_utils.py", line 380, in cmb_spectrogram_to_wave
    wave = librosa.resample(wave2, orig_sr=bp["sr"], target_sr=sr, res_type=wav_resolution)
  File "/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py", line 627, in resample
    util.valid_audio(y, mono=False)
  File "/usr/local/lib/python3.10/dist-packages/librosa/util/utils.py", line 314, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```
![bug](https://github.com/karaokenerds/python-audio-separator/assets/89285504/ab1af333-e3ec-4a6a-a923-8c108101f57c)
I have tried different audios in different formats and frequencies and have gotten the same result, so I think it is not the audio file. Both using it with GPU and CPU I get the same error.
This error appears in the colab I have made, if you can review it it would also be of great help, although it is basically just the installation and execution of the code without further ado.
Here is the link: https://colab.research.google.com/drive/1WZO66n44O8CZJAQ6Na-Ozj0TWlOPd5KA?usp=sharing

Any help would be greatly appreciated, whether I'm doing something wrong or if there is a bug in the code.

**Comment by beveradb** [comment]
Wow, that's wild, someone's created a ...GUI (basically) for `audio-separator` in Colab? 😅 

Anyway... yep, I get the same error with those specific models on my local machine, so it's not just you. 
I'm investigating and trying to fix right now, but can't promise when I'll resolve it.
There's lots of other models which definitely do work though - out of curiosity, may I ask what made you choose those specific models over others?

**Comment by Eddycrack864** [comment]
haha 😂 I know it can be weird for someone to make a GUI of something designed to be used CLI type. But I do it because I create colabs for people who don't know much about coding, so for those types of people it is easier to use something GUI-like.

The reason I found out those models didn't work is because I tried every single model. I tried them because many people use my colabs and maybe someone uses 3_HP-Vocal-UVR.pth or 4_HP-Vocal-UVR.pth (Although I know very well that almost no one uses those models).

Although the UVR-BVE-4B_SN-44100-1.pth model is very used, because it is the best model for removing backvocals (Better than 5_HP-Karaoke-UVR and 6_HP-Karaoke-UVR).

I hope you can resolve this bug soon 🙏

**Comment by beveradb** [comment]
Thanks for explaining, and for essentially doing a bunch of manual testing for me 😄 

(I still haven't gotten around to writing proper integration tests which verify the functionality in `audio-separator` actually works as expected for every model and configuration option, but that's on my TODO list: https://github.com/karaokenerds/python-audio-separator/blob/main/tests/TODO.txt#L11 )

I just assumed that anyone who wants a GUI would just use UVR itself!

Anyway, this is on my radar (I also want the BVE model to work) and I'll try and get to the bottom of what the issue is soon.

**Comment by venkat-sf** [comment]
Yes, I have seen this error for several clips too. But that doesn't seem to necessarily translate to bad output.

**Comment by Eddycrack864** [comment]
Since a few previous versions this was fixed, so I will close it as complete.

In the current version `0.17.5` all models work without errors, what a good job!
