### ISSUE TITLE
Using the same model and configuration, but the results are much worse than UVR5.6

### ISSUE THREAD

**Issue by yuchenooooooo** [karaokenerds/python-audio-separator#59]
**code：**
separator = Separator(model_file_dir=VrModelPath, output_dir=result_path, output_single_stem="instrumental",
                              sample_rate=sr, normalization_threshold=1.0, log_level=logging.DEBUG)
separator.load_model(model_filename='2_HP-UVR.pth')
output_file = separator.separate(source_path)
output_file_path = os.path.join(result_path, output_file[0])

I have been trying to compare the source code for a long time, but I still don't know why. The result is not as clear and transparent as UVR5, and it feels like the tone has been lowered

**Comment by yuchenooooooo** [comment]
The sound of the piano has been moved to the human voice, but the result of UVR5 will not be like this

**Comment by beveradb** [comment]
Sorry to hear that 😞 

I'll look into it when I next get some hobby project time - I've got a fork of UVR with refactored code and increased logging which I can use to compare a bit more closely, but it's still really hard and confusing as hell a lot of the time 😅 

Are you able to provide an example file which separates as expected in UVR but doesn't have good results from audio-separator despite using the same model and parameters?

One obvious thing worth noting is that I haven't yet implemented secondary model inferencing; e.g. see

- https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/architectures/vr_separator.py#L171
- https://github.com/karaokenerds/python-audio-separator/blob/main/audio_separator/separator/architectures/vr_separator.py#L216

PRs are of course very welcome if you can figure out the difference and fix it before I get around to it!

**Comment by yuchenooooooo** [comment]
I noticed your comment, but I’m not sure if my model is a secondary model. You can directly download the model I used on UVR5 (2_HP-UVR.pth)，but really, all models has that problem.
Then just run your code by default, and you will hear that the piano sound is obviously assigned to the vocal side. I compared the current progress with your tail processing, filtering, and file saving methods, and I couldn't find any problems except for the place you mentioned in your comment.
In addition, I found that your final output volume is smaller than that of UVR5, even if the normalized volume is set to 1.0. An example is that for the song "泡沫", 1.2 seems to be more suitable. Setting it to 1.2 and the volume of UVR5 will be the same, I guess This should be a problem of saving

**Comment by yuchenooooooo** [comment]
I now use python-demucs as an alternative, and the effect is okay. However, some VR models are irreplaceable. I hope you can find the cause of the problem. wish you good luck ：）

**Comment by beveradb** [comment]
Thanks - and of course, if anyone else wants to try and get to the bottom of the problem and figure it out that is always appreciated, I'm just a hobby coder doing this for free to help folks out after all!

In the meantime, have you tried the `MDX23C-8KFFT-InstVoc_HQ_2.ckpt` model? That's become my go-to for my own karaoke tracks and `audio-separator` supports it now - might be worth a try! 
Also `UVR-MDX-NET-Inst_HQ_4.onnx` is worth trying!

**Comment by yuchenooooooo** [comment]
My project can only run on the CPU, and I have to consider both speed and quality. I have tried the MDX23C and I think the sound quality is about the same as DEMUCS (it may also be a problem with my ears). Overall, DEMUCS is more suitable.

**Comment by beveradb** [comment]
No worries! FYI you can run the demucs models using `audio-separator` too 👀  (see `audio-separator -l` to list available) - e.g. `audio-separator --model_filename htdemucs_6s.yaml test.wav`

**Comment by yuchenooooooo** [comment]
Only VR models have problems, using MDX is not a problem, but MDX's Karaoke algorithm is not as good as VR. There is no echo when using UVR processing, but the audio speaker model is not a problem

**Comment by yuchenooooooo** [comment]
but the audio-sperator has problems

**Comment by yuchenooooooo** [comment]
i founded aggression must 0.05 instead of 5,code's default value is error

**Comment by beveradb** [comment]
Oh nice, thank you! Please raise a PR with the fix @yuchenooooooo 😄

**Comment by beveradb** [comment]
> i founded aggression must 0.05 instead of 5,code's default value is error

Are you sure? The UVR code seems to set it to 5 by default:

https://github.com/Anjok07/ultimatevocalremovergui/blob/master/gui_data/constants.py#L556

**Comment by yuchenooooooo** [comment]
https://github.com/karaokenerds/python-audio-separator/compare/main...yuchenooooooo:fix_aggression_param?expand=1
fix like it maybe useful

**Comment by beveradb** [comment]
Wow, thank you for pointing that out! Once again I find something new I missed in the UVR spaghetti code 😅 

I'll do some testing later today and get that fix merged in if all works well for me - though it's strange, because I've been getting decent results with some of the VR models already (e.g. `2_HP`) so I definitely want to make sure the new default value doesn't make a huge negative impact to existing workflows :)

**Comment by beveradb** [comment]
Hey @yuchenooooooo , just wanted to thank you again for pointing that out - I've now made the VR architecture default aggression fix as you suggested, in `audio-separator` version `0.17.1`

FYI, I've also now implemented support for the RoFormer models, I highly recommend trying them e.g. `audio-separator -m model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt` as the Mel-Roformer model performs better than all the other architectures so far in my opinion!
