### ISSUE TITLE
New version with a buggy demucs_separator

### ISSUE THREAD

**Issue by GeleiaComPepino** [karaokenerds/python-audio-separator#60]
Usage:

```
def separate_audio_files(input_dir, output_dir):
    inputFiles = [f for f in os.listdir(input_dir) if f.endswith('.wav')]
    for file in inputFiles:
        if not os.path.exists(os.path.join(output_dir, file.split('.wav')[0])):
            os.makedirs(os.path.join(output_dir, file.split('.wav')[0]))
        separator = Separator(output_dir=output_dir, log_level=2)
        separator.load_model(f'Kim_Vocal_2.onnx')
        separator.separate(os.path.join(input_dir, file))
```
Error:
**Traceback (most recent call last):
  File "\scripts\uvr.py", line 41, in <module>
    separate_audio_files(input_dir, output_dir)
  File "\scripts\uvr.py", line 12, in separate_audio_files
    separator.load_model(f'Kim_Vocal_2.onnx')
  File "\lib\site-packages\audio_separator\separator\separator.py", line 630, in load_model
    module = __import__("audio_separator.separator.architectures", fromlist=[separator_classes[model_type]])
  File "\lib\site-packages\audio_separator\separator\architectures\__init__.py", line 3, in <module>
    from .demucs_separator import DemucsSeparator
  File "\lib\site-packages\audio_separator\separator\architectures\demucs_separator.py", line 129
    match source_length:
          ^
SyntaxError: invalid syntax**
Log:
[log.txt](https://github.com/karaokenerds/python-audio-separator/files/14805866/log.txt)

**Comment by beveradb** [comment]
Well that's weird 😅  `Kim_Vocal_2.onnx` is an MDX model, not Demucs, so no Demucs code should even be running 🤔 

I've just run this test script locally in a clean conda environment without issues - see attached log.

```
import os

from audio_separator.separator import Separator


def separate_audio_files(input_dir, output_dir):
    inputFiles = [f for f in os.listdir(input_dir) if f.endswith(".wav")]
    for file in inputFiles:
        if not os.path.exists(os.path.join(output_dir, file.split(".wav")[0])):
            os.makedirs(os.path.join(output_dir, file.split(".wav")[0]))
        separator = Separator(output_dir=output_dir, log_level=2)
        separator.load_model(f"Kim_Vocal_2.onnx")
        separator.separate(os.path.join(input_dir, file))


separate_audio_files("testdir", "testdir")
```

[log.txt](https://github.com/karaokenerds/python-audio-separator/files/14808790/log.txt)

I don't have an easy way to test on Windows, but let me see if I can reproduce with your python version (3.9) - I think that is the most likely cause, since that's a very old (4 years) version of Python which probably doesn't support some of the syntax used in the Demucs code.

Why that code is running at all though (!) is another question!

**Comment by GeleiaComPepino** [comment]
Thanks, I will try changing the version.

**Comment by beveradb** [comment]
Hey, just wanted to thank you for raising this issue @GeleiaComPepino - it helped me find and fix a bug I didn't know existed (every model arch code was being loaded every time you load a model, whereas only the necessary model arch was supposed to be loaded!)

Here's the fix if you're curious: https://github.com/karaokenerds/python-audio-separator/commit/bcbbc5186fc1b5aeae5e9d137d2c68b894b6ef3d

I've just released a new version of `audio-separator` with the fix, and now if anyone tries to use a Demucs model with Python 3.9 they will get a very clear error message: "Demucs models require Python version 3.10 or newer."

But the rest of the model architectures still work on Python 3.9, so I'm leaving that Python version as officially supported still for flexibility for folks.

**Comment by GeleiaComPepino** [comment]
Hello, I'm glad my feedback was helpful in uncovering the bug.
Thanks for fast fix for this bug.
Helped a lot.
