### ISSUE TITLE
How to assign ffmpeg's encoding parameters?

### ISSUE THREAD

**Issue by owen8849** [karaokenerds/python-audio-separator#61]
I know i can save outfile to the format i set, but how do i assign the parameters of ffmpeg's? for example i want set the bitrate to 224k.

**Comment by beveradb** [comment]
There isn't a parameter for that yet - you're welcome to raise a PR implementing one ☺️

Alternatively, you could just set the output format to FLAC and do the lossy encode with ffmpeg as a separate command after the separation completes; would be pretty easy to integrate into a script too, just a single line shell execution of ffmpeg with the output filename passed in.

Hope that makes sense!

**Comment by beveradb** [comment]
I'm closing this as I haven't heard back from you and don't have any motivation to implement this myself.

Please feel free to raise a PR implementing parameter(s) to configure ffmpeg parameters if you want :)
