### ISSUE TITLE
add model_bs_roformer model support

### ISSUE THREAD

**Issue by superchaos** [karaokenerds/python-audio-separator#66]
when will model_bs_roformer_ep_937_sdr_10.5309.ckpt can support

**Comment by beveradb** [comment]
Whenever you (or someone else) implements support for it!

Please raise a PR 🙇

**Comment by beveradb** [comment]
I've just implemented support for the roformer models in audio-separator version `0.17` 🎉 

e.g. `audio-separator -m model_bs_roformer_ep_317_sdr_12.9755.ckpt input.flac`

You can list available models with `audio-separator --list_models`

**Comment by superchaos** [comment]
> I've just implemented support for the roformer models in audio-separator version `0.17` 🎉
> 
> e.g. `audio-separator -m model_bs_roformer_ep_317_sdr_12.9755.ckpt input.flac`
> 
> You can list available models with `audio-separator --list_models`

Awesome, it's really helpful. Thank you for your support!

**Comment by beveradb** [comment]
Glad to hear! May I ask what you're using it for? I'm always curious to hear about people's projects 😊

**Comment by superchaos** [comment]
> Glad to hear! May I ask what you're using it for? I'm always curious to hear about people's projects 😊

In the AI anchor project, I have utilized your capabilities by developing a simple interface that wraps your service as a REST API. Additionally, I have implemented the ability to orchestrate multiple models. It is suggested to incorporate similar capabilities into the project.

**Comment by superchaos** [comment]
> Glad to hear! May I ask what you're using it for? I'm always curious to hear about people's projects 😊

The business context is to create AI singers by utilizing voice separation and voice transformation techniques. The goal is to achieve the effect of an AI singer by separating the vocals and then applying voice modulation. After orchestrating multiple models, the results of the vocal separation have been satisfactory.
