### ISSUE TITLE
karaoke model sometimes cuts off the climax part of the song

### ISSUE THREAD

**Issue by yuchenooooooo** [karaokenerds/python-audio-separator#68]
I want to use a model that goes without harmony, the karaoke model sometimes cuts off the climax part of the song. How should you handle i

**Comment by beveradb** [comment]
Try different models! 😄 

I personally tend to find one of these is usually the cleanest pure instrumental separation, but they have different properties (as they're all different architectures):
- `MDX23C-8KFFT-InstVoc_HQ_2.ckpt`
- `UVR-MDX-NET-Inst_HQ_4.onnx`
- `2_HP-UVR.pth`

If you're trying to _keep_ more vocals in (e.g. backing vocals), try the `UVR_MDXNET_KARA_2.onnx` model.

I should say though, that right now (May 2024) the best performing model type which has only recently become readily available, `Mel-RoFormer` as detailed in this paper: https://arxiv.org/abs/2310.01809 isn't yet implemented in `audio-separator`.

I'm hoping to implement it soon if nobody else raises a PR doing so, though!

**Comment by beveradb** [comment]
I just implemented Mel-Roformer support in `audio-separator` version `0.17` - you might want to try it 😄 

e.g. `audio-separator -m model_bs_roformer_ep_317_sdr_12.9755.ckpt input.flac`
