### ISSUE TITLE
fast guitar processing mode

### ISSUE THREAD

**Issue by negeevmaks** [karaokenerds/python-audio-separator#71]
Congratulations! Can you let me know if there is a quick mode for processing the guitar?

**Comment by beveradb** [comment]
Not sure what you mean exactly, but the demucs models have the ability to separate only the guitar stem!

**Comment by beveradb** [comment]
Here's an example command for how to output just the Guitar stem btw:

`audio-separator -m htdemucs_6s.yaml --single_stem=Guitar tracks/abbawatchout30s.flac`

I'm going to close this as completed unless you can clarify what you mean and still need help :)

**Comment by negeevmaks** [comment]
Sorry, English is not my native language, so I may make mistakes. I really liked your project, you are a genius! I have a task to make a program that will listen to the computer's output and output notes to melodies. Your script added precision to my project so that the program that writes the notes does not highlight the guitar, and it was already separated, then the precision increases. It would be very interesting to see a new model from you that can split and write notes on this split, on whatever instrument it is.

**Comment by negeevmaks** [comment]
> demucs

Are there other guitar processing models besides demucs?

**Comment by beveradb** [comment]
That's complicated, see the 4-6 stems section in this doc for all the options!

https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?usp=drivesdk
